#159993328 Setup React-Redux
andela/ah-scorpion-frontend pull request #6
Opened 2018-08-28 12:14 UTC by blac-siren

**What does this PR do?**
Create the appropriate folder/file structure for React-Redux workflow.

**Description of Task to be completed?**
-  Create Reducer, Action folders and appropriate file for react-redux.

**How should this be manually tested?*
-  Clone this repository and branch to `ch-redux-setup-159993328`
- Run the server `npm start -s`
- Insert random text into the input box.
- You should see the random text below it. 😃

2018-08-28 12:46 UTC, hoslack approved these changes
I approve that @blac-siren and I have worked on a basic Redux setup and is working. We welcome any changes that might be requested though.

2018-08-28 13:08 UTC, munyili-samuel commented
@blac-siren Please give details of how this is done to make testing the PR easier
`Create Reducer, Action folders and appropriate file for react-redux`

2018-08-28 13:14 UTC, kisakyegordon commented
@blac-siren kindly attend to the conflicts - they are being brought some earlier commits. 
cc @hoslack

2018-08-28 13:17 UTC, munyili-samuel approved these changes
I have tested the PR and I am able to see the random text when I type on the text field.
Good work.

2018-08-28 13:20 UTC, RuthNjeri requested changes
The steps in your PR are incomplete. I am getting this error 
```
./src/index.js
Module not found: Can't resolve 'redux' in '/Users/waiganjo/Documents/ah-scorpion-UI/ah-scorpion-frontend/src'
```
add `npm install` as a step.

2018-08-28 13:25 UTC, zakhusayn commented
@RuthNjeri Thanks. I'll add it.

2018-08-28 14:27 UTC, lennykioko commented on src/App.js
> +import React, { Component } from "react";
According to Airbnb eslint standards, we should use single quotes except when writing JSX.

2018-08-28 14:39 UTC, lennykioko requested changes
Use single quotes except when writing JSX to ensure that we are conforming to Airbnb style guides.

2018-08-28 15:02 UTC, hoslack commented
Hey @blac-siren , some checks are still failing. Let's fix those first.

2018-08-28 18:28 UTC, davenjeru commented
The problem is found in `package.json` file. First of all, there are duplicate keys. Second, there is a missing comma which is bringing the error on TravisCI.

2018-08-29 07:21 UTC, RuthNjeri approved these changes

2018-08-29 07:29 UTC, hoslack requested changes
Hey @blac-siren , please remove the double quotation marks and replace with singles.

2018-08-29 09:12 UTC, hoslack approved these changes

2018-08-29 09:16 UTC, kipropbrian commented
What are the relevant Pivotal Tracker Stories?

2018-08-29 09:20 UTC, lennykioko approved these changes
Nice work implementing the feedback. Moving forward, we should work to conform to Airbnb style guides.

2018-08-29 09:50 UTC, kisakyegordon commented
@blac-siren kindly ensure the indenting is inorder - in particular `src/routes.test.js`

2018-08-29 09:59 UTC, merged